config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link      http://cakephp.org CakePHP(tm) Project
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */

use App\Controller\Component\NavigationComponent;
use Cake\Core\Plugin;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function ($routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Settings', 'action' => 'index']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

Router::scope('/api', function ($routes) {
    $routes->resources('Config');
});

NavigationComponent::addTab('Settings', '/');
NavigationComponent::addTab('Help', '/help');

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Category.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class Category extends Entity
{
    /**
     * Gets the category's panel width
     *
     * @param int $width The current width
     * @return int
     */
    protected function _getPanelWidth($width)
    {
        return isset($width) ? $width : 6;
    }
}

src/Model/Entity/Setting.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class Setting extends Entity
{

}

src/Model/Table/SettingsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Table;

class SettingsTable extends Table
{
    /**
     * @param array $config The config
     * @return void
     */
    public function initialize(array $config)
    {
        $this->belongsTo('Categories');
        $this->hasOne('SettingValues');
    }

    /**
     * Creates a settings table
     *
     * @param string $name The table name
     * @return void
     */
    public static function createSettingsTable($name)
    {
        /*
        $t = new \Cake\Database\Schema\Table($name . '_settings');

        $t->addColumn('id', 'integer');
        $t->addColumn('category_id', 'integer');
        $t->addColumn('name', 'string');
        $t->addColumn('required', [
            'type' => 'boolean',
            'default' => 0
        ]);
        $t->addColumn('default_value', 'string');
        $t->addColumn('options', 'text');

        $t->addConstraint('primary', [
            'type' => 'primary',
            'columns' => ['id']
        ]);

        $t->addIndex('category_id', [
            'columns' => ['category_id'],
            'type' => 'index'
        ]);

        $t->addConstraint('fk_' . $name . '_settings_categories_category_id', [
            'columns' => ['category_id'],
            'type' => 'foreign',
            'references' => ['categories', 'id'],
            'update' => 'cascade',
            'delete' => 'cascade'
        ]);

        $db = ConnectionManager::get('default');

        $queries = $t->createSql($db);
        foreach ($queries as $sql) {
            //$db->execute($sql);
        }
        */
    }
}

src/Controller/SettingsController.php
<?php
namespace App\Controller;

use App\Controller\BaseController\NavigationController;
use App\Model\Entity\Category;
use Cake\ORM\TableRegistry;

class SettingsController extends NavigationController
{
    public $components = ['Extension', 'Chromecast'];

    /**
     * Renders the settings index
     *
     * @return void
     */
    public function index()
    {
        $categories = $this->Extension->getCategories('settings');
        $this->renderModelView('index', $categories);
    }

    /**
     * Updates the settings with the submitted form data
     *
     * @return void
     */
    public function update()
    {
        if ($this->request->is('PUT')) {
            $data = $this->request->data;

            $categoriesTable = TableRegistry::get('Categories');
            $settingValuesTable = TableRegistry::get('SettingValues');

            $success = true;

            foreach ($data['categories'] as $id => $category) {
                $model = new Category([
                    'id' => $id,
                    'enabled' => $category['enabled']
                ]);

                $success = $categoriesTable->save($model);
            }

            $success = $success && $this->Extension->saveSettingValues($data, $settingValuesTable);

            if ($success) {
                $reloadMessage = '';

                if ($data['auto_refresh']) {
                    $this->Chromecast->refresh();

                    $reloadMessage = ' ' . __('If your Magic Mirror is currently running, it should automatically refresh very soon!');
                }

                $this->Flash->success(__('Successfully updated the settings!') . $reloadMessage);
            } else {
                $this->Flash->error(__('Unable to save your settings, are you connected to your database?'));
            }
        }

        $this->redirect(['action' => 'index']);
    }
}

src/Template/Settings/index.ctp
<?= $this->Form->create($model, ['url' => ['action' => 'update']]) ?>
    <div class="row">
        <?php $row = 0;
        foreach ($model as $id => $category): ?>
            <?= $category->panel_row != $row ? '</div><div class="row">' : '' ?>

            <div class="col-md-<?= $category->panel_width ?>">
                <div class="panel panel-primary">
                    <?php
                    if ($category->short_name != 'magic_mirror') {
                        echo $this->Settings->panelHeader(__($category->name), true, $id, $category->enabled);
                    } else {
                        echo $this->Settings->panelHeader(__($category->name));
                    }
                    ?>

                    <div class="panel-body">
                        <?= $this->Settings->inputs($id, $category->settings) ?>
                    </div>
                </div>
            </div>
        <?php $row = $category->panel_row;
        endforeach; ?>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= __('Actions') ?></h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 clearfix">
                            <?= $this->Form->button(__('Save Settings'), [
                                'name' => 'save_config',
                                'class' => 'btn-success pull-left',
                                'type' => 'submit'
                            ]) ?>

                            <?= $this->Form->button(__('Reload from Config'), [
                                'name' => 'reload_config',
                                'class' => 'btn-primary pull-right',
                                'type' => 'submit',
                                'data-tooltip' => 'tooltip',
                                'data-placement' => 'top',
                                'data-original-title' => __('Use this if you have modified the config manually')
                            ]) ?>
                        </div>
                    </div>

                    <?= $this->Form->input('auto_refresh', ['type' => 'checkbox', 'label' => __('Automatically refresh {0}', [__('{0} Magic Mirror', ['Chromecast'])]), 'default' => 1]) ?>
                </div>
            </div>
        </div>
    </div>
<?= $this->Form->end() ?>